const db = require('../config/db');
const oracledb = require('oracledb');

const storageLocationModel = {
  getLocations: async (facilityId, page = 1, limit = 20, searchId = null) => {
    const offset = (page - 1) * limit;
    let query = `
      SELECT RackID, locationno, warehouseid, userid
      FROM MasRacks
      WHERE warehouseid = :facilityId
    `;
    const binds = { facilityId };

    if (searchId) {
      query += ` AND RackID = :searchId `;
      binds.searchId = searchId;
    }

    query += `
      ORDER BY RackID
      OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY
    `;
    
    binds.offset = offset;
    binds.limit = limit;

    const result = await db.execute(query, binds, { outFormat: oracledb.OUT_FORMAT_OBJECT });
    return result.rows.map(row => ({
      RackID: row.RACKID,
      locationno: row.LOCATIONNO,
      warehouseid: row.WAREHOUSEID,
      userid: row.USERID
    }));
  },

  addLocation: async (facilityId, userId, locationNo) => {
    const query = `
      INSERT INTO MasRacks (
        RackID, locationno, warehouseid, userid, inserteddate, insertedby, machineip, syncstatus
      ) VALUES (
        MASRACKS_SEQ.NEXTVAL, :locationNo, :facilityId, :userId, SYSDATE, :userId, 'HCL-PC', 'N'
      )
    `;
    // We assume there's a sequence MASRACKS_SEQ or similar. Wait, if there isn't, how did C# do it?
    // C# didn't insert RackID in the query:
    // "insert into masracks (locationno,warehouseid,userid,inserteddate,insertedby,machineip,syncstatus)"
    // It seems RackID is generated by a trigger or auto-increment.
    const insertQuery = `
      INSERT INTO MasRacks (
        locationno, warehouseid, userid, inserteddate, insertedby, machineip, syncstatus
      ) VALUES (
        :locationNo, :facilityId, :userId, SYSDATE, :userId, 'HCL-PC', 'N'
      )
    `;
    const binds = { locationNo, facilityId, userId };
    const result = await db.execute(insertQuery, binds, { autoCommit: true });
    return result;
  },

  updateLocation: async (rackId, locationNo, userId) => {
    const query = `
      UPDATE MasRacks 
      SET locationno = :locationNo, updateddate = SYSDATE, updatedby = :userId
      WHERE RackID = :rackId
    `;
    const binds = { locationNo, userId, rackId };
    const result = await db.execute(query, binds, { autoCommit: true });
    return result;
  },

  deleteLocation: async (rackId) => {
    const query = `DELETE FROM MasRacks WHERE RackID = :rackId`;
    const result = await db.execute(query, { rackId }, { autoCommit: true });
    return result;
  }
};

module.exports = storageLocationModel;
